### PR TITLE
Initial design changes

### PR DESCRIPTION
**Pull request by kennethlarsen**
Initial design changes - I will keep working on the design but this should do the trick for now. Let me know what you think.

### CODE REVIEW

**Comment by 2016rshah** [comment]
Oh wow this is great, I didn't even know you were working on this! I have a few comments, but I can't wait to merge this.

Colors
=====

I really like the color you picked for the notification bar, would it be possible to switch the main header/footer color with the notification bar color? Like have notifications show up in the #F1654C and have the header footer show up in #00B5B5?

Header and Footer
==============

Also, would it be possible to make the footer a bit more inconspicous? Like maybe half the height of what it currently is or like the same size as the header. Right now I just think the footer is unnecessarily tall.


Mobile
=====
And finally, the header and footer don't center text vertically on mobile/small screens

Here's an example of what I'm talking about on the header
screen shot 2015-11-27 at 5 27 21 pm


And the corresponding footer

screen shot 2015-11-27 at 5 28 42 pm

**Comment by kennethlarsen** [comment]
Awesome! I will look into the changes :)

**Comment by kennethlarsen** [comment]
My latest commits should fix your requests :)

**Comment by 2016rshah** [comment]
Great work! If you would like to keep working on the project, I would love your help! Just let me know if you're up for it.

**Comment by kennethlarsen** [comment]
Thanks! Yeah I would love to help out.

**Comment by 2016rshah** [comment]
Okay well perhaps with the new design changes would you like to take a screenshot and update the README?

Also, do you have experience with Ruby and Rails, or are you mostly a designer?

**Comment by kennethlarsen** [comment]
I updated the readme with a new screenshot. 

I know some Ruby on Rails but I'm mainly a frontend developer so my Ruby on Rails code might not be the prettiest.

**Pull request merged**
